import type { AppLocale } from "@/i18n/routing";

const english = {
  action: "Action",
  adjustStock: "Record stock adjustment",
  all: "All",
  allLanguages: "All four complete",
  archived: "Archived",
  ageMaximum: "Latest possible year",
  ageMinimum: "Earliest possible year",
  ageVerified: "Age range is verified from evidence",
  altTextReady: "Image descriptions are reviewed for this language",
  applyValidRows: "Apply valid rows",
  archive: "Archive",
  archivedNotice:
    "This product is archived. Restore it from the product list before publishing it again.",
  autosaveHelp:
    "Edits are saved after a short pause. A version conflict stops the save instead of overwriting another manager’s work.",
  available: "Available",
  availableShort: "available",
  backCollections: "Back to collections",
  backEditor: "Back to product editor",
  backProducts: "Back to products",
  bulkActions: "Actions for selected products",
  bulkResult: "{succeeded} succeeded · {failed} need attention",
  cancelImport: "Cancel import",
  careCode: "Care code",
  careText: "Care guidance",
  catalogExport: "Catalog export",
  category: "Category",
  changeControl: "Change control",
  changeNote: "Reason for this change",
  changedFields: "Changed fields",
  code: "Collection code",
  collection: "Collection",
  collectionAdd: "Add to collection",
  collectionChangeNote: "Update collection details",
  collectionDetails: "Collection details",
  collectionRemove: "Remove from collection",
  collectionSummary: "{code} · {count} products",
  colors: "Colors (comma separated)",
  commerce: "Price, delivery, and initial inventory",
  compareSource: "Source language for comparison",
  compareVersions: "Compare v{current} with v{previous}",
  complete: "Complete",
  completeness: "{count} of 4 languages complete",
  condition: "Condition",
  confirm: "Confirm action",
  construction: "Construction",
  continueEditing: "Continue in the saved product",
  copiedWarning: "Review possible copied translations:",
  count: "{count} products on this page",
  createCollection: "Create collection",
  createCollectionNote: "Create collection",
  duplicateAsNew: "Duplicate as a new product",
  duplicateNotice:
    "Facts and copy were copied. Add a new SKU and unique URL slugs before saving.",
  csvFile: "Standard ÉPOCA CSV",
  dataPortability: "Bounded private files",
  defaultChangeNote: "Update catalog record",
  deliveryClass: "Delivery class",
  description: "Description",
  diameter: "Diameter (mm)",
  download: "Download",
  downloadErrors: "Download error report",
  downloadTemplate: "Download the standard CSV template",
  draft: "Draft",
  dryRun: "Validate before applying",
  editCollection: "Edit collection",
  exports: "Catalog exports",
  failed: "The change could not be completed safely.",
  featured: "Featured",
  filter: "Apply filters",
  importBatches: "Import history and previews",
  importHelp:
    "Upload a UTF-8 CSV using the standard headers. ÉPOCA validates every row and changes nothing until you apply the valid rows.",
  importPrivacy:
    "Source files and error reports stay private and expire through operations cleanup.",
  importSummary:
    "{rows} rows · {valid} valid · {invalid} invalid · {applied} applied",
  invalidRows: "Rows needing attention",
  inventory: "Inventory",
  inventoryEyebrow: "Authoritative availability",
  inventorySafety:
    "Reserved stock cannot be removed. Every correction keeps its reason and operator trail.",
  inventorySeparate:
    "Use the audited inventory adjustment panel below to change stock after creation.",
  inReview: "In review",
  languageDe: "German",
  languageEn: "English",
  languageKa: "Georgian",
  languageRu: "Russian",
  languages: "Languages",
  length: "Length (mm)",
  longDescription: "Full description",
  lowStock: "Low stock",
  materials: "Materials (comma separated)",
  handmade: "Handmade status",
  handmadeVerified: "Handmade status is verified from evidence",
  merchandising: "Product order and featured placement",
  merchandisingHelp:
    "Use the product list’s bulk action to add products, then arrange their public order here.",
  missing: "Missing",
  missingLocales: "Missing: {locales}",
  moveDown: "Move {name} down",
  moveUp: "Move {name} up",
  name: "Name",
  newCollection: "Create a collection",
  no: "No",
  noCollection: "Choose when required",
  noCollectionProducts:
    "No products are assigned. Add them from the product list.",
  noCollections: "No collections yet.",
  noImports: "No catalog CSV imports yet.",
  oldestFirst: "Oldest updated first",
  onHand: "On hand",
  orderStrategy: "Order strategy",
  origin: "Origin",
  originVerified: "Origin is verified from evidence",
  pile: "Pile",
  pileVerified: "Pile is verified from evidence",
  pagination: "Catalog pages",
  pending: "Pending",
  price: "Price",
  priceGel: "Price (GEL)",
  preview: "Preview product",
  previewWarning:
    "Staff preview: this is not public until the product passes readiness and is published.",
  product: "Product",
  provenance: "Provenance",
  provenanceSummary: "Verified provenance summary",
  provenanceVerified: "Provenance is verified from evidence",
  publish: "Publish",
  published: "Published",
  quantityDelta: "Quantity change (for example 2 or -1)",
  reason: "Reason",
  recentFirst: "Recently updated first",
  requestExport: "Request current scoped export",
  reserved: "Reserved",
  reservedShort: "reserved",
  restore: "Restore",
  row: "Row {row}",
  rows: "rows",
  save: "Save product",
  saveCollection: "Save collection",
  saveOrder: "Save product order",
  saved: "Catalog record saved.",
  savedViews: "Saved views",
  saveView: "Save current view",
  saving: "Saving…",
  scheduledAt: "Schedule publication time",
  schedule: "Schedule product",
  scheduleHelp:
    "The product must pass the same readiness checks as publishing. Times use Georgia time (UTC+4).",
  scheduleReason: "Reason for scheduling",
  scheduleSaved: "Product publication is scheduled.",
  scheduled: "Scheduled",
  search: "SKU or product name",
  searchText: "Discovery search terms",
  selectAll: "Select all products on this page",
  selectProduct: "Select {name}",
  selected: "{count} selected",
  seoDescription: "Search description",
  seoTitle: "Search title",
  shape: "Shape",
  shortDescription: "Short description",
  sku: "SKU",
  skuFirst: "SKU A–Z",
  slug: "URL slug",
  sort: "Sort",
  source: "Source",
  status: "Status",
  statusCancelled: "Cancelled",
  statusComplete: "Complete",
  statusFailed: "Failed",
  statusPending: "Pending",
  statusProcessing: "Processing",
  stockFirst: "Lowest stock first",
  stockModel: "Stock model",
  stocked: "Repeatable stock",
  styles: "Styles (comma separated)",
  translationStatus: "Translation status",
  translations: "Georgian, English, German, and Russian copy",
  unavailable: "Unavailable",
  unpublished: "Unpublished",
  unknown: "Unknown / omit",
  unpublish: "Unpublish",
  unique: "Unique piece",
  updated: "Updated",
  uploadCatalogCsv: "Upload and preview catalog data",
  validateUpload: "Upload and validate",
  validationIssues: "{count} validation issues",
  versionConflict:
    "Another manager changed this product. Reload to compare before saving again.",
  viewHistory: "View change history",
  viewName: "View name",
  viewSnapshot: "View recorded snapshot",
  width: "Width (mm)",
  working: "Working…",
  yes: "Yes",
} satisfies Record<string, string>;

const localized: Partial<Record<AppLocale, Partial<typeof english>>> = {
  de: {
    action: "Aktion",
    adjustStock: "Bestandskorrektur erfassen",
    all: "Alle",
    allLanguages: "Alle vier vollständig",
    archived: "Archiviert",
    available: "Verfügbar",
    availableShort: "verfügbar",
    backCollections: "Zurück zu Kollektionen",
    backEditor: "Zurück zum Produkteditor",
    backProducts: "Zurück zu Produkten",
    cancelImport: "Import abbrechen",
    category: "Kategorie",
    changeNote: "Grund der Änderung",
    collection: "Kollektion",
    colors: "Farben (kommagetrennt)",
    complete: "Vollständig",
    condition: "Zustand",
    confirm: "Aktion bestätigen",
    construction: "Herstellung",
    description: "Beschreibung",
    download: "Herunterladen",
    downloadErrors: "Fehlerbericht herunterladen",
    draft: "Entwurf",
    exports: "Katalogexporte",
    failed: "Die Änderung konnte nicht sicher abgeschlossen werden.",
    featured: "Hervorgehoben",
    filter: "Filter anwenden",
    inReview: "In Prüfung",
    inventory: "Bestand",
    languageDe: "Deutsch",
    languageEn: "Englisch",
    languageKa: "Georgisch",
    languageRu: "Russisch",
    languages: "Sprachen",
    lowStock: "Niedriger Bestand",
    longDescription: "Vollständige Beschreibung",
    materials: "Materialien (kommagetrennt)",
    missing: "Fehlt",
    missingLocales: "Fehlt: {locales}",
    name: "Name",
    noCollections: "Noch keine Kollektionen.",
    oldestFirst: "Älteste Aktualisierung zuerst",
    onHand: "Auf Lager",
    origin: "Herkunft",
    price: "Preis",
    product: "Produkt",
    published: "Veröffentlicht",
    publish: "Veröffentlichen",
    recentFirst: "Neueste Aktualisierung zuerst",
    reason: "Grund",
    reserved: "Reserviert",
    reservedShort: "reserviert",
    restore: "Wiederherstellen",
    save: "Produkt speichern",
    saveCollection: "Kollektion speichern",
    search: "SKU oder Produktname",
    scheduled: "Geplant",
    seoDescription: "Suchbeschreibung",
    seoTitle: "Suchtitel",
    shortDescription: "Kurzbeschreibung",
    skuFirst: "SKU A–Z",
    sort: "Sortierung",
    status: "Status",
    statusCancelled: "Abgebrochen",
    statusComplete: "Abgeschlossen",
    statusFailed: "Fehlgeschlagen",
    statusPending: "Ausstehend",
    statusProcessing: "In Bearbeitung",
    stockFirst: "Niedrigster Bestand zuerst",
    translationStatus: "Übersetzungsstatus",
    translations: "Georgische, englische, deutsche und russische Texte",
    unavailable: "Nicht verfügbar",
    unpublished: "Nicht veröffentlicht",
    updated: "Aktualisiert",
    working: "Wird ausgeführt…",
  },
  ru: {
    action: "Действие",
    adjustStock: "Записать корректировку остатка",
    all: "Все",
    allLanguages: "Все четыре языка заполнены",
    archived: "В архиве",
    available: "Доступно",
    availableShort: "доступно",
    backCollections: "Назад к коллекциям",
    backEditor: "Назад к редактору товара",
    backProducts: "Назад к товарам",
    cancelImport: "Отменить импорт",
    category: "Категория",
    changeNote: "Причина изменения",
    collection: "Коллекция",
    colors: "Цвета (через запятую)",
    complete: "Готово",
    condition: "Состояние",
    confirm: "Подтвердить действие",
    construction: "Техника изготовления",
    description: "Описание",
    download: "Скачать",
    downloadErrors: "Скачать отчёт об ошибках",
    draft: "Черновик",
    exports: "Экспорт каталога",
    failed: "Изменение не удалось безопасно завершить.",
    featured: "Избранное место",
    filter: "Применить фильтры",
    inReview: "На проверке",
    inventory: "Остатки",
    languageDe: "Немецкий",
    languageEn: "Английский",
    languageKa: "Грузинский",
    languageRu: "Русский",
    languages: "Языки",
    lowStock: "Мало на складе",
    longDescription: "Полное описание",
    materials: "Материалы (через запятую)",
    missing: "Не заполнено",
    missingLocales: "Не заполнено: {locales}",
    name: "Название",
    noCollections: "Коллекций пока нет.",
    oldestFirst: "Сначала давно обновлённые",
    onHand: "На складе",
    origin: "Происхождение",
    price: "Цена",
    product: "Товар",
    published: "Опубликован",
    publish: "Опубликовать",
    recentFirst: "Сначала недавно обновлённые",
    reason: "Причина",
    reserved: "Зарезервировано",
    reservedShort: "зарезервировано",
    restore: "Восстановить",
    save: "Сохранить товар",
    saveCollection: "Сохранить коллекцию",
    search: "SKU или название товара",
    scheduled: "Запланирован",
    seoDescription: "Описание для поиска",
    seoTitle: "Заголовок для поиска",
    shortDescription: "Краткое описание",
    skuFirst: "SKU А–Я",
    sort: "Сортировка",
    status: "Статус",
    statusCancelled: "Отменён",
    statusComplete: "Завершён",
    statusFailed: "Ошибка",
    statusPending: "Ожидает",
    statusProcessing: "Обрабатывается",
    stockFirst: "Сначала наименьший остаток",
    translationStatus: "Статус перевода",
    translations: "Тексты на грузинском, английском, немецком и русском",
    unavailable: "Недоступно",
    unpublished: "Не опубликован",
    updated: "Обновлено",
    working: "Выполняется…",
  },
  ka: {
    action: "მოქმედება",
    adjustStock: "მარაგის კორექტირების ჩაწერა",
    all: "ყველა",
    allLanguages: "ოთხივე ენა სრულადაა შევსებული",
    archived: "არქივშია",
    available: "ხელმისაწვდომი",
    availableShort: "ხელმისაწვდომია",
    backCollections: "კოლექციებზე დაბრუნება",
    backEditor: "პროდუქტის რედაქტორზე დაბრუნება",
    backProducts: "პროდუქტებზე დაბრუნება",
    cancelImport: "იმპორტის გაუქმება",
    category: "კატეგორია",
    changeNote: "ცვლილების მიზეზი",
    collection: "კოლექცია",
    colors: "ფერები (მძიმით გამოყოფილი)",
    complete: "სრული",
    condition: "მდგომარეობა",
    confirm: "მოქმედების დადასტურება",
    construction: "დამზადების ტექნიკა",
    description: "აღწერა",
    download: "ჩამოტვირთვა",
    downloadErrors: "შეცდომების ანგარიშის ჩამოტვირთვა",
    draft: "მონახაზი",
    exports: "კატალოგის ექსპორტები",
    failed: "ცვლილება უსაფრთხოდ ვერ დასრულდა.",
    featured: "გამორჩეული",
    filter: "ფილტრების გამოყენება",
    inReview: "შემოწმების პროცესში",
    inventory: "მარაგი",
    languageDe: "გერმანული",
    languageEn: "ინგლისური",
    languageKa: "ქართული",
    languageRu: "რუსული",
    languages: "ენები",
    lowStock: "მცირე მარაგი",
    longDescription: "სრული აღწერა",
    materials: "მასალები (მძიმით გამოყოფილი)",
    missing: "აკლია",
    missingLocales: "აკლია: {locales}",
    name: "სახელი",
    noCollections: "კოლექციები ჯერ არ არის.",
    oldestFirst: "ჯერ ძველი განახლებები",
    onHand: "საწყობში",
    origin: "წარმოშობა",
    price: "ფასი",
    product: "პროდუქტი",
    published: "გამოქვეყნებულია",
    publish: "გამოქვეყნება",
    recentFirst: "ჯერ ახალი განახლებები",
    reason: "მიზეზი",
    reserved: "დაჯავშნილი",
    reservedShort: "დაჯავშნილია",
    restore: "აღდგენა",
    save: "პროდუქტის შენახვა",
    saveCollection: "კოლექციის შენახვა",
    search: "SKU ან პროდუქტის სახელი",
    scheduled: "დაგეგმილია",
    seoDescription: "საძიებო აღწერა",
    seoTitle: "საძიებო სათაური",
    shortDescription: "მოკლე აღწერა",
    skuFirst: "SKU ანბანურად",
    sort: "დალაგება",
    status: "სტატუსი",
    statusCancelled: "გაუქმებულია",
    statusComplete: "დასრულებულია",
    statusFailed: "შეცდომაა",
    statusPending: "მოლოდინშია",
    statusProcessing: "მუშავდება",
    stockFirst: "ჯერ მცირე მარაგი",
    translationStatus: "თარგმანის სტატუსი",
    translations: "ქართული, ინგლისური, გერმანული და რუსული ტექსტი",
    unavailable: "მიუწვდომელი",
    unpublished: "გამოუქვეყნებელია",
    updated: "განახლებული",
    working: "მუშავდება…",
  },
};

export function getCatalogAdminLabels(
  locale: AppLocale,
): Record<string, string> {
  return { ...english, ...localized[locale] };
}

const statusLabelKeys: Record<string, keyof typeof english> = {
  archived: "archived",
  cancelled: "statusCancelled",
  complete: "statusComplete",
  draft: "draft",
  failed: "statusFailed",
  in_review: "inReview",
  leased: "statusProcessing",
  pending: "statusPending",
  published: "published",
  scheduled: "scheduled",
  unpublished: "unpublished",
};

export function getCatalogStatusLabel(
  labels: Record<string, string>,
  status: string,
) {
  const key = statusLabelKeys[status];
  return key ? labels[key] : status;
}
